{% set python_min = "3.10" %}
{% set name = "txl" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af43fdd59a4f5e6e9e8749bdf5c89f23da2ac3c1482d271d18e27ec26cc1880a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - fps >=0.2.1,<3.0.0
    - textual >=3.0.1,<4.0.0
    - tree_sitter
    - tree_sitter_languages

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - txl

about:
  home: https://codeberg.org/davidbrochart/jpterm/src/branch/main/txl
  summary: The plugin system for jpterm
  dev_url: https://codeberg.org/davidbrochart/jpterm/src/branch/main/txl
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
