{% set name = "txl" %}
{% set version = "0.2.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ef4919cfb77da5388148a19f11fc40f7898b1914679c4bbd44e168dd71a8c506

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - asphalt >=4.12.0,<5.0.0
    - textual >=0.74.0,<0.75.0
    - tree_sitter
    - tree_sitter_languages

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - txl

about:
  home: https://github.com/davidbrochart/jpterm/tree/main/txl
  summary: The plugin system for jpterm
  dev_url: https://github.com/davidbrochart/jpterm/tree/main/txl
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
