{% set python_min = "3.10" %}
{% set name = "txl" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 111a055af6b19bc812604873288319147415e253c2398e4f15a99bce4ce9d20f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - asphalt >=4.12.0,<5.0.0
    - textual >=1.0.0,<2.0.0
    - tree_sitter
    - tree_sitter_languages

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  requires:
    - python {{ python_min }}
  imports:
    - txl

about:
  home: https://github.com/davidbrochart/jpterm/tree/main/txl
  summary: The plugin system for jpterm
  dev_url: https://github.com/davidbrochart/jpterm/tree/main/txl
  license_file: LICENSE.txt
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
